
#
# This LookML file was generated by AtScale on 2024-04-05T08:50:02.662818332Z
#
# AtScale engine version: 2023.4.1.12728
# AtScale DesignCenter version: 2023.4.1.21138
# AtScale version: 2023.4.1.6713
# Organization: default
# Project: Hans SalesInsightsLOreal

connection: "atscale_hans"
label: "Hans SalesInsightsLOreal"


include: "/views/Hans_SalesInsightsLOreal/Hans_SalesInsightsLOreal.view.lkml"


explore: Hans_SalesInsightsLOreal {
  label: "Hans SalesInsightsLOreal"
}

