
#
# This LookML file was generated by AtScale on 2024-04-03T08:38:41.032944221Z
#
# AtScale engine version: 2023.4.1.12728
# AtScale DesignCenter version: 2023.4.1.21138
# AtScale version: 2023.4.1.6713
# Organization: default
# Project: SalesInsightsLOreal

connection: "atscalelorealpot"
label: "SalesInsightsLOreal"


include: "/views/SalesInsightsLOreal/InternetSalesCubeLOreal.view.lkml"


explore: InternetSalesCubeLOreal {
  label: "InternetSalesCubeLOreal"
}

