
#
# This LookML file was generated by AtScale on 2024-04-05T14:20:40.673469749Z
#
# AtScale engine version: 2023.4.1.12728
# AtScale DesignCenter version: 2023.4.1.21138
# AtScale version: 2023.4.1.6713
# Organization: default
# Project: Test MM

connection: "atscale_marco"
label: "Test MM"


include: "/views/Test_MM/Test_MM.view.lkml"

include: "/views/Test_MM/Shopfloor.view.lkml"

include: "/views/Test_MM/C-Level.view.lkml"


explore: Test_MM {
  label: "Test MM"
}

explore: Shopfloor {
  label: "Shopfloor"
}

explore: C_Level {
  label: "C-Level"
}

