
#
# This LookML file was generated by AtScale on 2024-04-08T09:34:38.019838548Z
#
# AtScale engine version: 2023.4.1.12728
# AtScale DesignCenter version: 2023.4.1.21138
# AtScale version: 2023.4.1.6713
# Organization: default
# Project: worksop francois

connection: "atscale_francois"
label: "worksop francois"


include: "/views/worksop_francois/worksop_francois.view.lkml"


explore: worksop_francois {
  label: "worksop francois"
}

