
#
# This LookML file was generated by AtScale on 2024-04-08T09:34:29.302363871Z
#
# AtScale engine version: 2023.4.1.12728
# AtScale DesignCenter version: 2023.4.1.21138
# AtScale version: 2023.4.1.6713
# Organization: default
# Project: Workshop Nathalie

connection: "atscale_nathalie"
label: "Workshop Nathalie"


include: "/views/Workshop_Nathalie/Workshop_Nathalie.view.lkml"


explore: Workshop_Nathalie {
  label: "Workshop Nathalie"
}

