
#
# This LookML file was generated by AtScale on 2024-04-08T09:34:25.398346826Z
#
# AtScale engine version: 2023.4.1.12728
# AtScale DesignCenter version: 2023.4.1.21138
# AtScale version: 2023.4.1.6713
# Organization: default
# Project: Workshop Marco

connection: "atscale_marco"
label: "Workshop Marco"


include: "/views/Workshop_Marco/Workshop_Marco.view.lkml"


explore: Workshop_Marco {
  label: "Workshop Marco"
}

