
#
# This LookML file was generated by AtScale on 2024-04-08T09:34:27.778689964Z
#
# AtScale engine version: 2023.4.1.12728
# AtScale DesignCenter version: 2023.4.1.21138
# AtScale version: 2023.4.1.6713
# Organization: default
# Project: Workshop Charles-Alban

connection: "atscale_charles-alban"
label: "Workshop Charles-Alban"


include: "/views/Workshop_Charles-Alban/Workshop_Charles-Alban.view.lkml"


explore: Workshop_Charles_Alban {
  label: "Workshop Charles-Alban"
}

