
#
# This LookML file was generated by AtScale on 2024-04-08T09:34:27.456784172Z
#
# AtScale engine version: 2023.4.1.12728
# AtScale DesignCenter version: 2023.4.1.21138
# AtScale version: 2023.4.1.6713
# Organization: default
# Project: Worshop POT 1 Rim

connection: "atscale_rim"
label: "Worshop POT 1 Rim"


include: "/views/Worshop_POT_1_Rim/Worshop_POT_1_Rim.view.lkml"


explore: Worshop_POT_1_Rim {
  label: "Worshop POT 1 Rim"
}

